from .svdquant_loader import (
    NODE_CLASS_MAPPINGS as _LOADER_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _LOADER_NAMES,
)
from .svdquant_lora import (
    NODE_CLASS_MAPPINGS as _LORA_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _LORA_NAMES,
)
from .svdquant_w4a4 import (
    NODE_CLASS_MAPPINGS as _W4A4_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _W4A4_NAMES,
)

NODE_CLASS_MAPPINGS = {**_LOADER_NODES, **_LORA_NODES, **_W4A4_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_LOADER_NAMES, **_LORA_NAMES, **_W4A4_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
