from .svdquant_diag import (
    NODE_CLASS_MAPPINGS as _DIAG_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _DIAG_NAMES,
)
from .svdquant_lora import (
    NODE_CLASS_MAPPINGS as _LORA_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _LORA_NAMES,
)
from .svdquant_w4a4 import (
    NODE_CLASS_MAPPINGS as _W4A4_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _W4A4_NAMES,
)

NODE_CLASS_MAPPINGS = {**_LORA_NODES, **_W4A4_NODES, **_DIAG_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_LORA_NAMES, **_W4A4_NAMES, **_DIAG_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
